services:
  i2p-blog:
    image: nginx:latest
    container_name: i2p-blog
    volumes:
      - /home/deepak/projects/i2p-blog/raaawr/public:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    restart: unless-stopped